#ifndef ARM_MOTION_INTERFACE_DEGS_H_
#define ARM_MOTION_INTERFACE_DEGS_H_
const int ARM_TEST_MODE =0;
const int ARM_GO_TO_PREDFINED_PRE_POSE=1;
const int ARM_DESCEND_20CM=2;
const int ARM_DEPART_20CM=3;

const int ARM_IS_SERVER_BUSY_QUERY = 1;
const int ARM_PLAN_PATH_QSTART_TO_ADES = 4;
const int ARM_PLAN_PATH_QSTART_TO_QGOAL = 5;
const int ARM_PLAN_PATH_ASTART_TO_QGOAL = 6;
const int ARM_PLAN_PATH_CURRENT_TO_PRE_POSE=7;

const int ARM_GET_Q_DATA = 8;

const int ARM_EXECUTE_PLANNED_PATH = 9;


//responses...
const int ARM_STATUS_UNDEFINED=0;
const int ARM_RECEIVED_AND_INITIATED_RQST=1;
const int ARM_REQUEST_REJECTED_ALREADY_BUSY=2;
const int ARM_SERVER_NOT_BUSY=3;
const int ARM_SERVER_IS_BUSY=4;
const int ARM_RECEIVED_AND_COMPLETED_RQST=5;
#endif
